"""family info removed on obs table

Revision ID: 161970b65fb5
Revises: 74d85febfe56
Create Date: 2024-12-31 06:30:19.201557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '161970b65fb5'
down_revision: Union[str, None] = '74d85febfe56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('observations', 'family')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('observations', sa.Column('family', sa.VARCHAR(), autoincrement=False, nullable=True))