"""specie_class added on observation table

Revision ID: 455d8ad90ce3
Revises: 5d4320602176
Create Date: 2024-12-16 14:04:10.997758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '455d8ad90ce3'
down_revision: Union[str, None] = '5d4320602176'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('observations', sa.Column('specie_class', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('observations', 'specie_class')
    