"""species table note field added

Revision ID: 4b9fc7eb444a
Revises: 455d8ad90ce3
Create Date: 2024-12-30 23:52:01.207736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b9fc7eb444a'
down_revision: Union[str, None] = '455d8ad90ce3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plant_species', sa.Column('specie_name_note', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plant_species', 'specie_name_note')
    # ### end Alembic commands ###
