"""specie names fiels updated plural

Revision ID: 6f2da4b097c0
Revises: 161970b65fb5
Create Date: 2025-01-23 14:34:42.582065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f2da4b097c0'
down_revision: Union[str, None] = '161970b65fb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('observations', sa.Column('plant_species_id', sa.Integer(), nullable=True))
    op.add_column('observations', sa.Column('species_class', sa.String(), nullable=True))
    op.drop_constraint('observations_plant_specie_id_fkey', 'observations', type_='foreignkey')
    op.create_foreign_key(None, 'observations', 'plant_species', ['plant_species_id'], ['id'])
    op.drop_column('observations', 'specie_class')
    op.drop_column('observations', 'plant_specie_id')
    op.add_column('plant_species', sa.Column('species_name_note', sa.String(), nullable=True))
    op.drop_column('plant_species', 'specie_name_note')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plant_species', sa.Column('specie_name_note', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('plant_species', 'species_name_note')
    op.add_column('observations', sa.Column('plant_specie_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('observations', sa.Column('specie_class', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'observations', type_='foreignkey')
    op.create_foreign_key('observations_plant_specie_id_fkey', 'observations', 'plant_species', ['plant_specie_id'], ['id'])
    op.drop_column('observations', 'species_class')
    op.drop_column('observations', 'plant_species_id')
    # ### end Alembic commands ###
