"""location info added on obs table

Revision ID: 95b93f7a5c29
Revises: 4b9fc7eb444a
Create Date: 2024-12-31 05:50:12.167570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95b93f7a5c29'
down_revision: Union[str, None] = '4b9fc7eb444a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('observations', sa.Column('country', sa.String(), nullable=True))
    op.add_column('observations', sa.Column('region', sa.String(), nullable=True))
    op.add_column('observations', sa.Column('continent', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('observations', 'continent')
    op.drop_column('observations', 'region')
    op.drop_column('observations', 'country')
    