"""month field added to observation table

Revision ID: b91c8389919b
Revises: 9980f82fba9d
Create Date: 2024-11-25 19:07:26.572990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b91c8389919b'
down_revision: Union[str, None] = '9980f82fba9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('observations', sa.Column('month', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('observations', 'month')