"""db obs table updated

Revision ID: c2bab2b91f01
Revises: 5477d06793b6
Create Date: 2024-10-27 00:44:39.811974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c2bab2b91f01'
down_revision: Union[str, None] = '5477d06793b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('observations', sa.Column('date', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('observations', 'date')
    # ### end Alembic commands ###
