"""lat and lon fields added to observation table

Revision ID: d55d6d7bb5c6
Revises: b91c8389919b
Create Date: 2024-11-25 19:19:32.658868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd55d6d7bb5c6'
down_revision: Union[str, None] = 'b91c8389919b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('observations', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('observations', sa.Column('lon', sa.Float(), nullable=True))
    op.execute("UPDATE observations SET lat = 0.0")
    op.alter_column('observations', 'lat', nullable=False)
    op.execute("UPDATE observations SET lon = 0.0")
    op.alter_column('observations', 'lon', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('observations', 'lon')
    op.drop_column('observations', 'lat')