"""family table added

Revision ID: d860195eb721
Revises: c2bab2b91f01
Create Date: 2024-11-12 15:32:47.313968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd860195eb721'
down_revision: Union[str, None] = 'c2bab2b91f01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('plant_species', sa.Column('family_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'plant_species', 'family', ['family_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'plant_species', type_='foreignkey')
    op.drop_column('plant_species', 'family_id')
    op.drop_table('family')
    # ### end Alembic commands ###
