export const BASE_API_URL = "http://212.56.40.148:8000"
export const AUTH_URL = BASE_API_URL + "/token"
export const USERINFO_URL = BASE_API_URL + "/users/details/me"
export const GEOSERVER_BASE_URL = "http://212.56.40.148:3002/geoserver"
export const DASHBOARD_DATA_URL = BASE_API_URL + "/data/dashboard"
export const PLANT_DATA_URL = BASE_API_URL + "/data/get"
export const FAMILY_DATA_URL = BASE_API_URL + "/data/family?fname="
export const FAMILY_DATA_MAX_URL = BASE_API_URL + "/data/family/max?fname="
export const FAMILY_NAME_SEARCH =  BASE_API_URL + "/data/family/search?search_filter="
export const MONTHLY_DISTRO_URL = BASE_API_URL + "/data/monthly/distro"
export const REGION_DISTRO_URL = BASE_API_URL + "/data/region/distro"
export const YEAR_DISTRO_URL = BASE_API_URL + "/data/yearly/distro"
export const PLANT_TOP_URL = BASE_API_URL + "/data/plants/top"
export const POIN_DATA_URL = BASE_API_URL + "/map/obs"

