export const BASE_API_URL = "http://212.56.40.148:8000"
export const AUTH_URL = BASE_API_URL + "/token"
export const USERINFO_URL = BASE_API_URL + "/users/details/me"
export const GEOSERVER_BASE_URL = "http://212.56.40.148:3002/geoserver"
export const DASHBOARD_DATA_URL = BASE_API_URL + "/data/dashboard"
export const PLANT_DATA_URL = BASE_API_URL + "/data/get"